apiVersion: cs.opensourceways.com/v1alpha1
kind: CodeServer
metadata:
  name: codeserver-lxdcontainer
  namespace: default
spec:
  runtime: lxd
  subdomain: codeserver-lxdcontainer
  image: "opensourceway/playground-lxc-launcher:sha-2b12023"
  storageSize: "10Gi"
  storageName: "default"
  ingressBandwidth: "10M"
  egressBandwidth: "100k"
  inactiveAfterSeconds: 0
  recycleAfterSeconds: 1800
  readinessProbe:
    httpGet:
      path: "/active-time"
      port: 80
    initialDelaySeconds: 20
    periodSeconds: 3
    timeoutSeconds: 3
  workspaceLocation: "/workspace"
  envs:
    - name: GOTTY_ONLY_ENABLE_BACKEND_WS_SERVER
      value: "false"
    - name: DISABLE_AUTO_UPDATE
      value: "true"
    - name: GOTTY_CREDENTIAL
      value: {{ .NamePassword }}
    - name: GOTTY_MAX_CONNECTION
      value: "10"
    - name: COMMUNITY_EMAIL
      value: {{ .ContactEmail }}
    - name: GOTTY_WS_ORIGIN
      value: ".*"
    - name: GOTTY_PERMIT_WRITE
      value: "true"
    - name: GOTTY_PROCESS_WORKING_DIR
      value: "/home/coder"
    - name: LAUNCHER_ADDITIONAL_CONFIG #keep
      value: raw.lxc=lxc.apparmor.profile=unconfined,security.nesting=false
    - name: LAUNCHER_INSTANCE_PROFILES #keep
      value: container
    - name: LAUNCHER_IMAGE_ALIAS #keep
      value: openeuler20.03-lts-sp3-container-x86
    - name: TERM
      value: xterm
  connectProbe: "/active-time"
  privileged: false
  resources:
    requests:
      cpu: "1"
      memory: "1000Mi"