apiVersion: cs.opensourceways.com/v1alpha1
kind: CodeServer
metadata:
  name: opengaussweb-server-sample
  namespace: opengauss-tryme
spec:
  runtime: generic
  subdomain: opengaussweb-server-sample
  image: "opensourceway/opengauss-pgweb:0.0.9"
  inactiveAfterSeconds: 0
  recycleAfterSeconds: 1800
  command:
    - /bin/bash
    - -c
    - |
      whoami
      source ~/.bashrc
      /home/gauss/openGauss/install/bin/gs_ctl start -D /home/gauss/openGauss/data
      gsql -d postgres  -p 5432  -h 127.0.0.1  -U gauss -W openGauss2022 -c "CREATE USER opengauss with createdb IDENTIFIED BY 'openGauss2022'"
      /usr/bin/pgweb --bind=0.0.0.0 --listen=8080 --url "postgres://opengauss:openGauss2022@0.0.0.0:5432/postgres?sslmode=disable"
  connectProbe: "/"
  containerPort: "8080"
  privileged: false
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
  connectionString: "https://%s.%s/"